# Parameters related to building rocblas
ARG base_image

FROM ${base_image}
LABEL maintainer="andrew.chapman@amd.com"

ARG user_uid

# Install dependent packages
RUN yum install -y \
    sudo \
    rock-dkms \
    rocm_smi64 \
    centos-release-scl \
    devtoolset-7 \
    ca-certificates \
    git \
    cmake3 \
    make \
    gcc-gfortran \
    unzip \
    wget \
    pkgconfig \
    python27 \
    python36 \
    python36-devel \
    python36-pip \
    python36-pytest \
    python36-setuptools \
    llvm7.0-devel \
    llvm7.0-static \
    libcxx-devel \
    boost-devel \
    zlib-devel \ 
    libgomp \
    numactl-libs \
    rpm-build \
    deltarpm 

RUN echo '#!/bin/bash' | tee /etc/profile.d/devtoolset7.sh && echo \
    'source scl_source enable devtoolset-7' >>/etc/profile.d/devtoolset7.sh

# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G video --shell /bin/bash jenkins && \
    echo '%video ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    chmod 400 /etc/sudoers.d/sudo-nopasswd

RUN wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz && \
    tar -xvzf *.gz && cd googletest* && mkdir build && cd build && cmake3 .. && \
    make -j && cp -r ../googletest/include /usr/local/include && \
    cp lib/libgtest*.a /usr/local/lib

RUN git clone https://github.com/Reference-LAPACK/lapack.git && cd lapack && \
    mkdir build && cd build && cmake3 -DCMAKE_INSTALL_LIBDIR=/usr/local/lib/lapack && \
    cmake3 --build . --target install
